### ISSUE TITLE
isModule 改成ture 运行不了

### ISSUE THREAD

**Issue by sinbara0813** [wutq/AndroidModuleDemo#1]
报 main/ui/loaddingActivity 不存在

**Comment by wutq** [comment]
改了需要Sync 一下才会生效
main/ui/loaddingActivity 不存在  你看下配置文件清单的路径 我修改过包名  loaddingActivity的包路径是com.wss.module.main.ui.loading.LoadingActivity

**Comment by qinyang1018** [comment]
@wutq   改成true后我也运行不了   报错如下
![image](https://user-images.githubusercontent.com/15726024/48966380-5d92ac00-f00b-11e8-8413-e2a3f0719bd3.png)
使用
com.android.tools.build:gradle:3.2.1
https\://services.gradle.org/distributions/gradle-4.6-all.zip

**Comment by xing16** [comment]
> @wutq 改成true后我也运行不了 报错如下
> ![image](https://user-images.githubusercontent.com/15726024/48966380-5d92ac00-f00b-11e8-8413-e2a3f0719bd3.png)
> 使用
> com.android.tools.build:gradle:3.2.1
> https://services.gradle.org/distributions/gradle-4.6-all.zip



我也遇到这个错，不知道怎么解决

**Comment by xing16** [comment]
![qq 20181209220608](https://user-images.githubusercontent.com/11294252/49698448-e0685900-fbfe-11e8-94a6-fbfbdd584e01.png)


module 作为 application 运行时，报错，请教大神

**Comment by wutq** [comment]
组件模式运行需要注意的几个点
1.修改完config.gradle中的ismodule需要 sysc一下才生效。
2.查看一下组件模式运行下加载的AndroidManifest，以及AndroidManifest中是否配置了组件模式下的程序入口activity。

**Comment by xing16** [comment]
这些都有配置，好像是 butterknife 报错，作为 组件运行时，编不过，报 R2 找不到，作为 application 时没问题，

**Comment by wutq** [comment]
那看一下butterknife的版本 目前我使用的8.4.0其他版本没有试过。

**Comment by xing16** [comment]
classpath 'com.android.tools.build:gradle:3.0.1' 版本降到 3.0.1  才可以

**Comment by wutq** [comment]
嗯嗯   最近比较忙 这块东西没有仔细研究。
