### ISSUE TITLE
as 3.4错误

### ISSUE THREAD

**Issue by gatspy** [wutq/AndroidModuleDemo#10]
在as更新到3.4build错误.

**Comment by gatspy** [comment]
这个问题解决了, 是由于新版本as使用的ndk版本引起了 `No toolchains found in the NDK toolchains folder for ABI with prefix`, 需要升级`android gradle build tool` 到`3.1+`, 然后就导致了一系列问题.

**Comment by wutq** [comment]
嗯嗯，我这一会没有升级AS 目前使用的3.0.1版本。
