### ISSUE TITLE
运行时报错了

### ISSUE THREAD

**Issue by martinwen** [wutq/AndroidModuleDemo#11]
![image](https://user-images.githubusercontent.com/16153404/90798186-308c3e00-e344-11ea-9a23-3e75226a7d7c.png)
![image](https://user-images.githubusercontent.com/16153404/90798257-47329500-e344-11ea-8eca-7cdb09cf14e8.png)

**Comment by LKCodeLab** [comment]
安裝 lombok 插件

**Comment by wutq** [comment]
误删除了一个文件在2020年08月28日 14:55的这版本已经提交了，你重新clone一下

**Comment by martinwen** [comment]
> 误删除了一个文件在2020年08月28日 14:55的这版本已经提交了，你重新clone一下

重新下载了，运行还是报之前的错误
