### ISSUE TITLE
  isModule = true

### ISSUE THREAD

**Issue by lixiongh-hou** [wutq/AndroidModuleDemo#12]
作者您好，最近在看组件化开发知识，看到了您的文章，我吧  isModule = true后同步出现了`Unable to resolve dependency for ':app@debugAndroidTest/compileClasspath': Could not resolve project :module_market.
Show Details
Affected Modules: AndroidModuleDemo-app`错误，请问还需要修改那个地方吗

**Comment by wutq** [comment]
一半出现这种情况9成9是android studio抽风了， 你clean project 试下，要是还不行就删掉每个模块 build目录下的东西，然后清除缓存，重启AS Invalidate Caches / Restart ，功能是好使的

**Comment by lixiongh-hou** [comment]
可以了，我删除.gradle和.idea文件重新启动AS一下就行了，android studio真的是太搞了
