### ISSUE TITLE
提问!

### ISSUE THREAD

**Issue by ChristingLi** [wutq/AndroidModuleDemo#4]
之前看过一篇文章说尽量不要在组件化中使用数据库,不知道是为什么?

**Comment by wutq** [comment]
这个好像不太清楚诶。可能是防止组件开发模式下数据的不同步吧，实际开发中或多或少都会用到数据库，可以把数据库往下层 放到base中处理

**Comment by ChristingLi** [comment]
O(∩_∩)O谢谢
