### ISSUE TITLE
Build报apache错是什么原因？

### ISSUE THREAD

**Issue by kevin161** [wutq/AndroidModuleDemo#6]
Error:Could not resolve all files for configuration ':common_base:debugAnnotationProcessorClasspath'.
> Could not download commons-collections4.jar (org.apache.commons:commons-collections4:4.1)
   > Could not get resource 'https://jcenter.bintray.com/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar'.
      > Could not GET 'https://jcenter.bintray.com/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar'.
         > Remote host closed connection during handshake

**Comment by shanksiscool** [comment]
推出，关闭AS看看，我也刚刚遇到handshake问题。重新打开，接着就是慢慢的sync gradle，看它报什么提醒。我刚刚遇到，AS提醒buildToolVersion要update，common_base/build.gradle下的第一行`comple`替换成`implementation`之类的小修改

**Comment by shanksiscool** [comment]
> Error:Could not resolve all files for configuration ':common_base:debugAnnotationProcessorClasspath'.
> 
> > Could not download commons-collections4.jar (org.apache.commons:commons-collections4:4.1)
> > Could not get resource 'https://jcenter.bintray.com/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar'.
> > > Could not GET 'https://jcenter.bintray.com/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar'.
> > > Remote host closed connection during handshake

有时候可能是网络问题的，

**Comment by kevin161** [comment]
> > Error:Could not resolve all files for configuration ':common_base:debugAnnotationProcessorClasspath'.
> > > Could not download commons-collections4.jar (org.apache.commons:commons-collections4:4.1)
> > > Could not get resource 'https://jcenter.bintray.com/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar'.
> > > > Could not GET 'https://jcenter.bintray.com/org/apache/commons/commons-collections4/4.1/commons-collections4-4.1.jar'.
> > > > Remote host closed connection during handshake
> 
> 有时候可能是网络问题的，

试了不行

**Comment by wutq** [comment]
jar包下不下来，肯定是网络的锅，或者你把jar包手动下载了扔到你本地的库里去
