### ISSUE TITLE
举手🙋

### ISSUE THREAD

**Issue by ChristingLi** [wutq/AndroidModuleDemo#7]
请问当
Model独自作为整个项目开发时,ButterKnife需要使用R2;作为单独项目开发又要使用R;这样最后合并Module的时候还要把R文件全部替换吗?

**Comment by ChristingLi** [comment]
是不是有点麻烦..

**Comment by wutq** [comment]
不用的，写的时候R2写法，无论是独立运行，还是组合运行都可以，不用去修改， 你可以把Demo拉下来 自己跑一把看下效果就知道了。

**Comment by ChristingLi** [comment]
我照着文章开发整个项目是R2是可用的 
单独编译model就找不到R2了...尴尬 可能是我写错吧 我对着Model再看看吧
