### ISSUE TITLE
假如网络不好，用户退出activity，网络请求怎么办

### ISSUE THREAD

**Issue by liguangze** [wutq/AndroidModuleDemo#9]
这个时候应该是取消网络请求，但是在baseActivity里面是不是没有，加上应该怎么处理呢，指定的取消某个请求

**Comment by wutq** [comment]
嗯，在activity销毁的时候取消网络请求即可，Demo中写的没有那么全面

**Comment by wutq** [comment]
@liguangze  网络框架已经替换成新的了 这个问题已经在新版本中得到解决
